### ISSUE TITLE
README is missing

### ISSUE THREAD

**Issue by jounathaen** [ncm2/ncm2-markdown-subscope#2]
There is a short explainatory line in the project description, but a README with a short explanation and maybe even an example would be great 👍 

(Comming from the ncm2 wiki, I don't even know what a subscope is...)

**Comment by nkakouros** [comment]
I cannot get this working too. This is what I have in my vimrc:

```
Plug 'ncm2/ncm2'
Plug 'roxma/nvim-yarp'
Plug 'ncm2/ncm2-syntax'
Plug 'shougo/neco-syntax'
Plug 'ncm2/ncm2-markdown-subscope'
Plug 'plasticboy/vim-markdown'
```

Then I do `PlugInstall` and do:

```
:new test.md
i
```sh
declare
```

There are no completion suggestions for the word `declare`. Editing a shell script directly does work though.

What else is needed?

**Comment by roxma** [comment]
@tterranigma  try adding this into your vimrc:
```vim
let g:necosyntax#max_syntax_lines=2000 " or higher
call ncm2#override_source('syntax', {'subscope_enable': 1})
```

**Comment by nkakouros** [comment]
That worked! So, if I get this correctly, if I want completion suggestions from a completion source to show in a subscope, then I need to make sure `subscope_enable` is set to 1 for that source, right?

**Comment by roxma** [comment]
@tteranigma

My mistake. you don't need `subscope_enable` and `ncm2-markdown-subscope` to get neco-syntax&ncm2-syntax to work. All you need in this case is setting `max_syntax_lines`.

> if I want completion suggestions from a completion source to show in a subscope, then I need to make sure subscope_enable is set to 1 for that source, right?

No. It depends. `subscope_enable` tells ncm2 to notify the source for completion in the subscope and pass some extra information to the source. But the source may not be able to handle it properly.

**Comment by nkakouros** [comment]
Oh alright. Thanks for clarification!
